COMMON: &common
  ROUTEROS:
    HOST: ${ROUTEROS_HOST}
    USER: ${ROUTEROS_USER}
    PASSWORD: ${ROUTEROS_PASS}

DEVELOPMENT: &development
  <<: *common
  SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI}

TESTING: &testing
  SQLALCHEMY_DATABASE_URI: ${SQLALCHEMY_DATABASE_URI_TESTING}