"""empty message

Revision ID: 10377eb2d235
Revises: 43bc5aed6290
Create Date: 2024-08-07 14:39:01.623191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10377eb2d235'
down_revision = '43bc5aed6290'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('fast',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('protocolo', sa.String(length=10), nullable=True),
    sa.Column('origen', sa.String(length=22), nullable=False),
    sa.Column('destino', sa.String(length=22), nullable=False),
    sa.Column('identificador', sa.String(length=15), nullable=False),
    sa.Column('alerta', sa.Text(), nullable=False),
    sa.Column('clasificacion', sa.Text(), nullable=False),
    sa.Column('fecha', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('fast')
    # ### end Alembic commands ###
