"""base

Revision ID: 43bc5aed6290
Revises: 
Create Date: 2024-07-13 17:03:57.208365

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43bc5aed6290'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('prioridad', sa.Integer(), nullable=True),
    sa.Column('protocolo', sa.String(length=10), nullable=True),
    sa.Column('origen', sa.String(length=22), nullable=False),
    sa.Column('destino', sa.String(length=22), nullable=False),
    sa.Column('su_id', sa.String(length=15), nullable=False),
    sa.Column('alerta', sa.Text(), nullable=False),
    sa.Column('clasificacion', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('alerts')
    # ### end Alembic commands ###
