"""empty message

Revision ID: a2beed029253
Revises: 50f6fd0283a5
Create Date: 2024-08-12 17:20:56.145155

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2beed029253'
down_revision = '50f6fd0283a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ip_origen', sa.String(length=22), nullable=False))
        batch_op.add_column(sa.Column('puerto_origen', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('ip_destino', sa.String(length=22), nullable=False))
        batch_op.add_column(sa.Column('puerto_destino', sa.Integer(), nullable=False))
        batch_op.drop_column('origen')
        batch_op.drop_column('destino')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destino', sa.VARCHAR(length=22), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('origen', sa.VARCHAR(length=22), autoincrement=False, nullable=False))
        batch_op.drop_column('puerto_destino')
        batch_op.drop_column('ip_destino')
        batch_op.drop_column('puerto_origen')
        batch_op.drop_column('ip_origen')

    # ### end Alembic commands ###
