"""empty message

Revision ID: f81b182c946c
Revises: a2beed029253
Create Date: 2024-08-23 09:40:24.521981

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81b182c946c'
down_revision = 'a2beed029253'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fast', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reciente', sa.Boolean(), nullable=True))

    with op.batch_alter_table('ids_rules', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ids_rules', schema=None) as batch_op:
        batch_op.alter_column('active',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    with op.batch_alter_table('fast', schema=None) as batch_op:
        batch_op.drop_column('reciente')

    # ### end Alembic commands ###
